p11-glue/p11-kit

- trust/anchor.c
While 'trust anchor' command tries to add CKA_TRUSTED attribute to any
object, it is only valid for a certificate object.
https://bugzilla.redhat.com/show_bug.cgi?id=1158926
> trust: Don't add CKA_TRUSTED to extension object

- common/Makefile.am
- common/compat.c
- common/test-argv.c
This fixes platform independent issues found while porting to Windows (#45).
> Minor fixes to libp11-common

- NEWS
- configure.ac
We have got quite a few bug fixes and features since the last release.  Let's plan a new release.
> Release 0.23.4

- configure.ac
- p11-kit/test-transport.c
A couple of FreeBSD-related build fixes for issues I stopped with 0.23.4.
> FreeBSD build fixes

- NEWS
- configure.ac
- p11-kit/Makefile.am
- p11-kit/server.c
- p11-kit/test-rpc.c
Let's plan on the new release.
> Release 0.23.6

- p11-kit/server.c
Reported by Mantas Mikulėnas in:
https://bugs.freedesktop.org/show_bug.cgi?id=101212
> server: Avoid use-after-free

- p11-kit/test-rpc.c
The value given to p11_rpc_buffer_add_ulong_value() must be a pointer
of CK_ULONG.  Similarly, the value returned from
p11_rpc_buffer_get_ulong_value() must be converted to CK_ULONG before
comparison.
Reported by Andreas Metzler in:
https://lists.freedesktop.org/archives/p11-glue/2017-July/000665.html
> test: Fix failure on 32-bit big endian platform

- common/compat.c
> build: Include <stdint.h> for SIZE_MAX

- p11-kit/rpc-server.c
Previously, when "p11-kit server" started only with a token URI, it
couldn't properly find and initialize the module which provides the
token.  This was because of the wrong order of cleanup of the modules.
> server: Make it work only when token URI is provided

- p11-kit/modules.c
Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>
> p11_kit_modules_load*: enhanced documentation on flags

- .travis.yml
- build/wine-wrapper.sh
- common/runtime.c
- common/test-runtime.c
- p11-kit/fixtures/system-modules/win32/seven.module
- p11-kit/test-messages.sh
> Fix build and test failure on mingw

- common/debug.c
- common/library.c
- common/message.c
- common/test-message.c
- configure.ac
> library: Use dedicated locale object for printing error

- p11-kit/test-server.sh
> test: Avoid exceeding maximum pathname length of Unix socket

- .travis.yml
- .travis/linux/after_failure.sh
- .travis/linux/after_success.sh
- .travis/linux/before_install.sh
- .travis/linux/install.sh
- .travis/linux/script.sh
- .travis/osx/after_failure.sh
- .travis/osx/before_install.sh
- .travis/osx/script.sh
- common/runtime.c
- common/test-runtime.c
This depends on #167.
Fixes #166.
> travis: Enable CI on macOS

- common/compat.c
- common/compat.h
- common/library.c
- common/library.h
- configure.ac
- p11-kit/Makefile.am
- p11-kit/client-init.c
- p11-kit/proxy-init.c
- trust/module.c
This implements the suggestion in: https://bugzilla.redhat.com/show_bug.cgi?id=985495#c0
> Remove hard dependency on libpthread

- p11-kit/virtual.c
On some circumstances (such as when loading p11-kit-proxy from httpd),
it is known that creation of libffi closure always fails, due to
SELinux policy.  Although this is harmless, it pollutes the journal
and gives wrong hints when troubleshooting.  This patch changes the
order of preference of libffi vs pre-compiled closures to avoid that.
> virtual: Prefer fixed closures to libffi closures

- configure.ac
> build: Require pkg.m4 >= 0.29 at bootstrap

- trust/extract-jks.c
For reproducible builds, accept a define timestamp for the java
keystore.
See https://reproducible-builds.org/docs/source-date-epoch/
> trust/extract-jks.c: also honor SOURCE_DATE_EPOCH time

- p11-kit/conf.c
Suggested by Bastien Nocera:
https://bugzilla.redhat.com/show_bug.cgi?id=1688583
> conf: Ignore user configuration if the program is running as root

- common/meson.build
- meson.build
- p11-kit/meson.build
- trust/meson.build
> build: Make threads dependency more explicit

- p11-kit/rpc-message.c
- trust/utf8.c
> build: Fix undefined behavior in left shift

- p11-kit/test-rpc.c
On ILP32 platforms CK_ULONG is 32-bit and 64-bit values are truncated.
This patch determins the usable value from SIZEOF_UNSIGNED_LONG.
Also, for consistency, use UINTxx_MAX for other accessors.
Reported by Jeffrey Walton in:
https://github.com/p11-glue/p11-kit/issues/289
> test-rpc: Suppress compiler warning on ILP32 platforms

- common/meson.build
- meson.build
- meson_options.txt
- p11-kit/meson.build
- trust/meson.build
> meson: Add options to disable NLS and building test programs

- doc/manual/meson.build
Fixes https://github.com/p11-glue/p11-kit/issues/331
> meson: Allow building manpages without gtk-doc

- common/compat.c
- common/library.c
Reported by Viktor Ashirov in:
https://bugzilla.redhat.com/show_bug.cgi?id=1905581
> compat: Pacify ASan complaints on intentionally leaked buffer

- trust/enumerate.c
Thanks in advance for reviewing.
> Fix minor typo

- .packit.yaml
\+
```
packit: clean up
* synced_files: that's default so we can drop it
* create-archive is not used for propose_downstream
```
> packit: fedora renamed master branch to rawhide

- .github/workflows/build-image.yml
- ci/Dockerfile
> ci: Integrate Docker image building to GitHub workflow

- .github/workflows/test.yaml
> ci: Use Docker image from the same repository

- NEWS
- configure.ac
- meson.build
> Release 0.24.1

- trust/base64.c
- trust/enumerate.c
- trust/save.c
This series suppresses the remaining warnings reported by LGTM.com.
> Silence warnings spotted by LGTM.com

- ci/Dockerfile
> Switch to using Gcovr insteado of LCOV

- .github/actions/basic-autotools/action.yaml
- .github/workflows/test.yaml
- trust/test-extract.sh
> .github/workflows/test.yaml: Enable CI on macOS

- po/POTFILES.in
Signed-off-by: Zoltan Fridrich <zfridric@redhat.com>
> po: Add p11-kit/print-config.c to POTFILES.in

- p11-kit/proxy.c
This plumbs proxy around CK_INTERFACE instead of CK_FUNCTION_LIST. That way we can eliminate global `interfaces` as well as reduce the number of wrapped functions created by C_GetInterface.
> proxy: Simplify interface lookup logic

- p11-kit/Makefile.am
- p11-kit/meson.build
- p11-kit/mock-module-v3-ep.c
- p11-kit/mock-module-v3-ep2.c
- p11-kit/mock-module-v3-ep4.c
Adds new mock modules for testing purposes of pkcs#11 3.0
> Add pkcs#11 3.0 mock modules for testing

- p11-kit/proxy.c
Following up the commit 040ab19faaec28203c673599f51815c7d146f929, this adds a missing check on interface version requested at GetInterface, and also a NULL check on pVersion.  Reported by Zoltán Fridrich.
> proxy: Check requested interface version upon GetInterface

- p11-kit/Makefile.am
- p11-kit/fixtures/package-modules/four-v3.module
- p11-kit/fixtures/package-modules/four.module
- p11-kit/meson.build
- p11-kit/test-log.c
- p11-kit/test-managed.c
- p11-kit/test-mock.c
- p11-kit/test-proxy.c
- p11-kit/test-proxy3.c
- p11-kit/test-rpc.c
- p11-kit/test-transport.c
- p11-kit/test-virtual.c
Adds tests for pkcs#11 3.0 proxy module
> Add tests for pkcs#11 3.0 proxy module

- bash-completion/p11-kit
- bash-completion/trust
- doc/manual/p11-kit.xml
* adds documenation for print-config command
* adds bash-completion for print-config command
* adds bash-completion for check-format command
Closes #484
> Document print-config command

- p11-kit/modules.c
> Small format fix in p11-kit/modules.c

- configure.ac
- p11-kit/meson.build
- p11-kit/p11-kit-1.pc.in
> Make the proxy_module extension in pkg-config .pc file adaptable

- bash-completion/meson.build
- doc/manual/meson.build
- meson.build
bumps the meson version to 0.51
Closes #569
> Fix meson warnings

- bash-completion/p11-kit
- po/POTFILES.in
Filling in some missing parts for list-tokens command.
> Add list-tokens into po/POTFILES.in and autocompletion

- doc/manual/p11-kit.xml
- p11-kit/delete-object.c
This is to adjust the p11-kit documentation after all of the behavioral changes done to the object and profile sub-commands.
> revise documentation of object and profile commands

- common/hex.c
> Add include for stdint.h to common/hex.c

- p11-kit/export-object.c
- trust/x509.c
> Fix errors when compiling with -std=gnu23
